version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    # command: --local-infile=0 --sql-mode="STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --max-allowed-packet=32M --innodb-buffer-pool-size=256MB
    command: --sql-mode="STRICT_ALL_TABLES" --innodb-buffer-pool-size=256MB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./data:/var/lib/mysql
  phabricator:
    depends_on:
      - mysql
    build: ./php-apache
    entrypoint: bash -c "/usr/local/bin/entrypoint.sh apache2-foreground;"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    # network_mode: host
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_PORT: 3306
      PHABRICATOR_BASE_URI: http://127.0.0.1
      PHABRICATOR_ADDITIONAL_URI: http://docker-phabricator-wmf_phabricator_1